<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.2 setup script
 * Date: Thu, 09 Jul 2020 00:28:13 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: aws-liceo [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'aws-liceo';
$cfg['Servers'][$i]['host'] = 'dbliceopatria.c8pnflsni9gj.us-east-1.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['compress'] = true;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['Console']['Mode'] = 'collapse';
$cfg['Console']['DarkTheme'] = true;
$cfg['blowfish_secret'] = 'nJRje@e#La Gloria de Dios Es la Inteligencia#EeZ\\La razon de la sin razon que a mi razon fervorece\\UfN?ir(^S4CL5-N@KsLd@';
$cfg['DefaultLang'] = 'es';
$cfg['ServerDefault'] = 1;
$cfg['Export']['compression'] = 'gzip';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['PersistentConnections'] = true;
$cfg['ShowCreateDb'] = false;
$cfg['ShowServerInfo'] = false;
$cfg['ShowChgPassword'] = false;
$cfg['DefaultTransformations']['Substring'] = array (
  0 => '0',
  1 => 'all',
  2 => '…',
);
$cfg['DefaultTransformations']['External'] = array (
  0 => '0',
  1 => '-f /dev/null -i -wrap -q',
  2 => '1',
  3 => '1',
);
$cfg['DefaultTransformations']['PreApPend'] = array (
);
$cfg['DefaultTransformations']['DateFormat'] = array (
  0 => '0',
  1 => 'local',
);
$cfg['DefaultTransformations']['Inline'] = array (
  0 => '100',
  1 => '100',
);
$cfg['DefaultTransformations']['TextImageLink'] = array (
  0 => '100',
  1 => '50',
);
$cfg['DefaultTransformations']['TextLink'] = array (
);
$cfg['FirstLevelNavigationItems'] = 150;
$cfg['VersionCheck'] = false;
$cfg['MaxDbList'] = 200;
$cfg['MaxTableList'] = 500;
?>